version: '3'
services:
  app:
    container_name: berat_app
    build:
        context: .
        dockerfile: Dockerfile
    ports: 
        - 8080:8080 
    restart: on-failure
    depends_on:
        database:
            condition: service_healthy      

  database:
    image: postgres:latest
    container_name: berat_db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        timeout: 5s
        retries: 10

volumes:
    database_postgres: